# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r_github_packages: petermeissner/r6extended
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel
